version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
    command: sh -c "yarn run start"
    restart: always
    environment:
      VIRTUAL_HOST: chainlist.wallet3.io
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: chainlist.wallet3.io
      LETSENCRYPT_EMAIL: lilong@chainbow.io
    ports:
      - "3000:3000"
    networks:
      - shared

networks:
  default:
    external: true
    name: shared
